export interface CountryCode {
  code: string;
  dial: string;
  flag: string;
  name: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "AF", dial: "+93", flag: "🇦🇫", name: "Afghanistan" },
  { code: "AL", dial: "+355", flag: "🇦🇱", name: "Albanie" },
  { code: "DZ", dial: "+213", flag: "🇩🇿", name: "Algérie" },
  { code: "AD", dial: "+376", flag: "🇦🇩", name: "Andorre" },
  { code: "AO", dial: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "AG", dial: "+1268", flag: "🇦🇬", name: "Antigua-et-Barbuda" },
  { code: "AR", dial: "+54", flag: "🇦🇷", name: "Argentine" },
  { code: "AM", dial: "+374", flag: "🇦🇲", name: "Arménie" },
  { code: "AU", dial: "+61", flag: "🇦🇺", name: "Australie" },
  { code: "AT", dial: "+43", flag: "🇦🇹", name: "Autriche" },
  { code: "AZ", dial: "+994", flag: "🇦🇿", name: "Azerbaïdjan" },
  { code: "BS", dial: "+1242", flag: "🇧🇸", name: "Bahamas" },
  { code: "BH", dial: "+973", flag: "🇧🇭", name: "Bahreïn" },
  { code: "BD", dial: "+880", flag: "🇧🇩", name: "Bangladesh" },
  { code: "BB", dial: "+1246", flag: "🇧🇧", name: "Barbade" },
  { code: "BY", dial: "+375", flag: "🇧🇾", name: "Biélorussie" },
  { code: "BE", dial: "+32", flag: "🇧🇪", name: "Belgique" },
  { code: "BZ", dial: "+501", flag: "🇧🇿", name: "Belize" },
  { code: "BJ", dial: "+229", flag: "🇧🇯", name: "Bénin" },
  { code: "BT", dial: "+975", flag: "🇧🇹", name: "Bhoutan" },
  { code: "BO", dial: "+591", flag: "🇧🇴", name: "Bolivie" },
  { code: "BA", dial: "+387", flag: "🇧🇦", name: "Bosnie-Herzégovine" },
  { code: "BW", dial: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "BR", dial: "+55", flag: "🇧🇷", name: "Brésil" },
  { code: "BN", dial: "+673", flag: "🇧🇳", name: "Brunei" },
  { code: "BG", dial: "+359", flag: "🇧🇬", name: "Bulgarie" },
  { code: "BF", dial: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "BI", dial: "+257", flag: "🇧🇮", name: "Burundi" },
  { code: "CV", dial: "+238", flag: "🇨🇻", name: "Cap-Vert" },
  { code: "KH", dial: "+855", flag: "🇰🇭", name: "Cambodge" },
  { code: "CM", dial: "+237", flag: "🇨🇲", name: "Cameroun" },
  { code: "CA", dial: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "CF", dial: "+236", flag: "🇨🇫", name: "République centrafricaine" },
  { code: "TD", dial: "+235", flag: "🇹🇩", name: "Tchad" },
  { code: "CL", dial: "+56", flag: "🇨🇱", name: "Chili" },
  { code: "CN", dial: "+86", flag: "🇨🇳", name: "Chine" },
  { code: "CO", dial: "+57", flag: "🇨🇴", name: "Colombie" },
  { code: "KM", dial: "+269", flag: "🇰🇲", name: "Comores" },
  { code: "CG", dial: "+242", flag: "🇨🇬", name: "Congo" },
  { code: "CD", dial: "+243", flag: "🇨🇩", name: "RD Congo" },
  { code: "CR", dial: "+506", flag: "🇨🇷", name: "Costa Rica" },
  { code: "CI", dial: "+225", flag: "🇨🇮", name: "Côte d'Ivoire" },
  { code: "HR", dial: "+385", flag: "🇭🇷", name: "Croatie" },
  { code: "CU", dial: "+53", flag: "🇨🇺", name: "Cuba" },
  { code: "CY", dial: "+357", flag: "🇨🇾", name: "Chypre" },
  { code: "CZ", dial: "+420", flag: "🇨🇿", name: "Tchéquie" },
  { code: "DK", dial: "+45", flag: "🇩🇰", name: "Danemark" },
  { code: "DJ", dial: "+253", flag: "🇩🇯", name: "Djibouti" },
  { code: "DM", dial: "+1767", flag: "🇩🇲", name: "Dominique" },
  { code: "DO", dial: "+1809", flag: "🇩🇴", name: "République dominicaine" },
  { code: "EC", dial: "+593", flag: "🇪🇨", name: "Équateur" },
  { code: "EG", dial: "+20", flag: "🇪🇬", name: "Égypte" },
  { code: "SV", dial: "+503", flag: "🇸🇻", name: "Salvador" },
  { code: "GQ", dial: "+240", flag: "🇬🇶", name: "Guinée équatoriale" },
  { code: "ER", dial: "+291", flag: "🇪🇷", name: "Érythrée" },
  { code: "EE", dial: "+372", flag: "🇪🇪", name: "Estonie" },
  { code: "SZ", dial: "+268", flag: "🇸🇿", name: "Eswatini" },
  { code: "ET", dial: "+251", flag: "🇪🇹", name: "Éthiopie" },
  { code: "FJ", dial: "+679", flag: "🇫🇯", name: "Fidji" },
  { code: "FI", dial: "+358", flag: "🇫🇮", name: "Finlande" },
  { code: "FR", dial: "+33", flag: "🇫🇷", name: "France" },
  { code: "GA", dial: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "GM", dial: "+220", flag: "🇬🇲", name: "Gambie" },
  { code: "GE", dial: "+995", flag: "🇬🇪", name: "Géorgie" },
  { code: "DE", dial: "+49", flag: "🇩🇪", name: "Allemagne" },
  { code: "GH", dial: "+233", flag: "🇬🇭", name: "Ghana" },
  { code: "GR", dial: "+30", flag: "🇬🇷", name: "Grèce" },
  { code: "GD", dial: "+1473", flag: "🇬🇩", name: "Grenade" },
  { code: "GT", dial: "+502", flag: "🇬🇹", name: "Guatemala" },
  { code: "GN", dial: "+224", flag: "🇬🇳", name: "Guinée" },
  { code: "GW", dial: "+245", flag: "🇬🇼", name: "Guinée-Bissau" },
  { code: "GY", dial: "+592", flag: "🇬🇾", name: "Guyana" },
  { code: "HT", dial: "+509", flag: "🇭🇹", name: "Haïti" },
  { code: "HN", dial: "+504", flag: "🇭🇳", name: "Honduras" },
  { code: "HK", dial: "+852", flag: "🇭🇰", name: "Hong Kong" },
  { code: "HU", dial: "+36", flag: "🇭🇺", name: "Hongrie" },
  { code: "IS", dial: "+354", flag: "🇮🇸", name: "Islande" },
  { code: "IN", dial: "+91", flag: "🇮🇳", name: "Inde" },
  { code: "ID", dial: "+62", flag: "🇮🇩", name: "Indonésie" },
  { code: "IR", dial: "+98", flag: "🇮🇷", name: "Iran" },
  { code: "IQ", dial: "+964", flag: "🇮🇶", name: "Irak" },
  { code: "IE", dial: "+353", flag: "🇮🇪", name: "Irlande" },
  { code: "IT", dial: "+39", flag: "🇮🇹", name: "Italie" },
  { code: "JM", dial: "+1876", flag: "🇯🇲", name: "Jamaïque" },
  { code: "JP", dial: "+81", flag: "🇯🇵", name: "Japon" },
  { code: "JO", dial: "+962", flag: "🇯🇴", name: "Jordanie" },
  { code: "KZ", dial: "+7", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "KE", dial: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "KI", dial: "+686", flag: "🇰🇮", name: "Kiribati" },
  { code: "KP", dial: "+850", flag: "🇰🇵", name: "Corée du Nord" },
  { code: "KR", dial: "+82", flag: "🇰🇷", name: "Corée du Sud" },
  { code: "KW", dial: "+965", flag: "🇰🇼", name: "Koweït" },
  { code: "KG", dial: "+996", flag: "🇰🇬", name: "Kirghizistan" },
  { code: "LA", dial: "+856", flag: "🇱🇦", name: "Laos" },
  { code: "LV", dial: "+371", flag: "🇱🇻", name: "Lettonie" },
  { code: "LB", dial: "+961", flag: "🇱🇧", name: "Liban" },
  { code: "LS", dial: "+266", flag: "🇱🇸", name: "Lesotho" },
  { code: "LR", dial: "+231", flag: "🇱🇷", name: "Liberia" },
  { code: "LY", dial: "+218", flag: "🇱🇾", name: "Libye" },
  { code: "LI", dial: "+423", flag: "🇱🇮", name: "Liechtenstein" },
  { code: "LT", dial: "+370", flag: "🇱🇹", name: "Lituanie" },
  { code: "LU", dial: "+352", flag: "🇱🇺", name: "Luxembourg" },  { code: "MO", dial: "+853", flag: "🇲🇴", name: "Macao" },
  { code: "MG", dial: "+261", flag: "🇲🇬", name: "Madagascar" },
  { code: "MW", dial: "+265", flag: "🇲🇼", name: "Malawi" },
  { code: "MY", dial: "+60", flag: "🇲🇾", name: "Malaisie" },
  { code: "MV", dial: "+960", flag: "🇲🇻", name: "Maldives" },
  { code: "ML", dial: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "MT", dial: "+356", flag: "🇲🇹", name: "Malte" },
  { code: "MH", dial: "+692", flag: "🇲🇭", name: "Îles Marshall" },
  { code: "MR", dial: "+222", flag: "🇲🇷", name: "Mauritanie" },
  { code: "MU", dial: "+230", flag: "🇲🇺", name: "Maurice" },
  { code: "MX", dial: "+52", flag: "🇲🇽", name: "Mexique" },
  { code: "FM", dial: "+691", flag: "🇫🇲", name: "Micronésie" },
  { code: "MD", dial: "+373", flag: "🇲🇩", name: "Moldavie" },
  { code: "MC", dial: "+377", flag: "🇲🇨", name: "Monaco" },
  { code: "MN", dial: "+976", flag: "🇲🇳", name: "Mongolie" },
  { code: "ME", dial: "+382", flag: "🇲🇪", name: "Monténégro" },
  { code: "MA", dial: "+212", flag: "🇲🇦", name: "Maroc" },
  { code: "MZ", dial: "+258", flag: "🇲🇿", name: "Mozambique" },
  { code: "MM", dial: "+95", flag: "🇲🇲", name: "Myanmar" },
  { code: "NA", dial: "+264", flag: "🇳🇦", name: "Namibie" },
  { code: "NR", dial: "+674", flag: "🇳🇷", name: "Nauru" },
  { code: "NP", dial: "+977", flag: "🇳🇵", name: "Népal" },
  { code: "NL", dial: "+31", flag: "🇳🇱", name: "Pays-Bas" },
  { code: "NZ", dial: "+64", flag: "🇳🇿", name: "Nouvelle-Zélande" },
  { code: "NI", dial: "+505", flag: "🇳🇮", name: "Nicaragua" },
  { code: "NE", dial: "+227", flag: "🇳🇪", name: "Niger" },
  { code: "NG", dial: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "MK", dial: "+389", flag: "🇲🇰", name: "Macédoine du Nord" },
  { code: "NO", dial: "+47", flag: "🇳🇴", name: "Norvège" },
  { code: "OM", dial: "+968", flag: "🇴🇲", name: "Oman" },
  { code: "PK", dial: "+92", flag: "🇵🇰", name: "Pakistan" },
  { code: "PW", dial: "+680", flag: "🇵🇼", name: "Palaos" },
  { code: "PS", dial: "+970", flag: "🇵🇸", name: "Palestine" },
  { code: "PA", dial: "+507", flag: "🇵🇦", name: "Panama" },
  { code: "PG", dial: "+675", flag: "🇵🇬", name: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", dial: "+595", flag: "🇵🇾", name: "Paraguay" },
  { code: "PE", dial: "+51", flag: "🇵🇪", name: "Pérou" },
  { code: "PH", dial: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "PL", dial: "+48", flag: "🇵🇱", name: "Pologne" },
  { code: "PT", dial: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "QA", dial: "+974", flag: "🇶🇦", name: "Qatar" },
  { code: "RO", dial: "+40", flag: "🇷🇴", name: "Roumanie" },
  { code: "RU", dial: "+7", flag: "🇷🇺", name: "Russie" },
  { code: "RW", dial: "+250", flag: "🇷🇼", name: "Rwanda" },
  { code: "KN", dial: "+1869", flag: "🇰🇳", name: "Saint-Kitts-et-Nevis" },
  { code: "LC", dial: "+1758", flag: "🇱🇨", name: "Sainte-Lucie" },
  { code: "VC", dial: "+1784", flag: "🇻🇨", name: "Saint-Vincent-et-les-Grenadines" },
  { code: "WS", dial: "+685", flag: "🇼🇸", name: "Samoa" },
  { code: "SM", dial: "+378", flag: "🇸🇲", name: "Saint-Marin" },
  { code: "ST", dial: "+239", flag: "🇸🇹", name: "Sao Tomé-et-Príncipe" },
  { code: "SA", dial: "+966", flag: "🇸🇦", name: "Arabie saoudite" },
  { code: "SN", dial: "+221", flag: "🇸🇳", name: "Sénégal" },
  { code: "RS", dial: "+381", flag: "🇷🇸", name: "Serbie" },
  { code: "SC", dial: "+248", flag: "🇸🇨", name: "Seychelles" },
  { code: "SL", dial: "+232", flag: "🇸🇱", name: "Sierra Leone" },
  { code: "SG", dial: "+65", flag: "🇸🇬", name: "Singapour" },
  { code: "SK", dial: "+421", flag: "🇸🇰", name: "Slovaquie" },
  { code: "SI", dial: "+386", flag: "🇸🇮", name: "Slovénie" },
  { code: "SB", dial: "+677", flag: "🇸🇧", name: "Îles Salomon" },
  { code: "SO", dial: "+252", flag: "🇸🇴", name: "Somalie" },
  { code: "ZA", dial: "+27", flag: "🇿🇦", name: "Afrique du Sud" },
  { code: "SS", dial: "+211", flag: "🇸🇸", name: "Soudan du Sud" },
  { code: "ES", dial: "+34", flag: "🇪🇸", name: "Espagne" },
  { code: "LK", dial: "+94", flag: "🇱🇰", name: "Sri Lanka" },
  { code: "SD", dial: "+249", flag: "🇸🇩", name: "Soudan" },
  { code: "SR", dial: "+597", flag: "🇸🇷", name: "Suriname" },
  { code: "SE", dial: "+46", flag: "🇸🇪", name: "Suède" },
  { code: "CH", dial: "+41", flag: "🇨🇭", name: "Suisse" },
  { code: "SY", dial: "+963", flag: "🇸🇾", name: "Syrie" },
  { code: "TW", dial: "+886", flag: "🇹🇼", name: "Taïwan" },
  { code: "TJ", dial: "+992", flag: "🇹🇯", name: "Tadjikistan" },
  { code: "TZ", dial: "+255", flag: "🇹🇿", name: "Tanzanie" },
  { code: "TH", dial: "+66", flag: "🇹🇭", name: "Thaïlande" },
  { code: "TL", dial: "+670", flag: "🇹🇱", name: "Timor oriental" },
  { code: "TG", dial: "+228", flag: "🇹🇬", name: "Togo" },
  { code: "TO", dial: "+676", flag: "🇹🇴", name: "Tonga" },
  { code: "TT", dial: "+1868", flag: "🇹🇹", name: "Trinité-et-Tobago" },
  { code: "TN", dial: "+216", flag: "🇹🇳", name: "Tunisie" },
  { code: "TR", dial: "+90", flag: "🇹🇷", name: "Turquie" },
  { code: "TM", dial: "+993", flag: "🇹🇲", name: "Turkménistan" },
  { code: "TV", dial: "+688", flag: "🇹🇻", name: "Tuvalu" },
  { code: "UG", dial: "+256", flag: "🇺🇬", name: "Ouganda" },
  { code: "UA", dial: "+380", flag: "🇺🇦", name: "Ukraine" },
  { code: "AE", dial: "+971", flag: "🇦🇪", name: "Émirats arabes unis" },
  { code: "GB", dial: "+44", flag: "🇬🇧", name: "Royaume-Uni" },
  { code: "US", dial: "+1", flag: "🇺🇸", name: "États-Unis" },
  { code: "UY", dial: "+598", flag: "🇺🇾", name: "Uruguay" },
  { code: "UZ", dial: "+998", flag: "🇺🇿", name: "Ouzbékistan" },
  { code: "VU", dial: "+678", flag: "🇻🇺", name: "Vanuatu" },
  { code: "VA", dial: "+379", flag: "🇻🇦", name: "Vatican" },
  { code: "VE", dial: "+58", flag: "🇻🇪", name: "Venezuela" },
  { code: "VN", dial: "+84", flag: "🇻🇳", name: "Viêt Nam" },
  { code: "YE", dial: "+967", flag: "🇾🇪", name: "Yémen" },
  { code: "ZM", dial: "+260", flag: "🇿🇲", name: "Zambie" },
  { code: "ZW", dial: "+263", flag: "🇿🇼", name: "Zimbabwe" },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES.find(c => c.code === "TN") || COUNTRY_CODES[0];

export const TUNISIA_DIAL_CODE = "+216";
