import {
  ArrowLeftRight,
  GraduationCap,
  Users,
  CreditCard,
  Receipt,
  FolderOpen,
  Wallet,
  History,
  TrendingUp,
  DollarSign,
  Banknote,
} from "lucide-react-native";
import { BankingColors } from "./banking-colors";

export const INITIAL_QUICK_ACTIONS = [
  {
    id: "send",
    icon: ArrowLeftRight,
    titleKey: "menu.transfers",
    descKey: "qa_send_desc",
    color: BankingColors.primary,
    bg: "#FFF5F3" },
  {
    id: "schooling",
    icon: GraduationCap,
    titleKey: "schooling.title",
    descKey: "qa_schooling_desc",
    color: "#D97842",
    bg: "#FFF7ED" },
  {
    id: "beneficiaries",
    icon: Users,
    titleKey: "beneficiaries.title",
    descKey: "qa_beneficiaries_desc",
    color: "#16A34A",
    bg: "#F0FDF4" },
  {
    id: "cards",
    icon: CreditCard,
    titleKey: "menu.myCards",
    descKey: "qa_cards_desc",
    color: "#7C3AED",
    bg: "#F5F3FF" },
  {
    id: "transfers",
    icon: History,
    titleKey: "qa_transfers_title",
    descKey: "qa_transfers_desc",
    color: "#6B7280",
    bg: "#F3F4F6" },
  {
    id: "billers",
    icon: Receipt,
    titleKey: "menu.billPayments",
    descKey: "qa_billers_desc",
    color: "#9333EA",
    bg: "#FAF5FF" },
  {
    id: "edocs",
    icon: FolderOpen,
    titleKey: "edocs.title",
    descKey: "qa_edocs_desc",
    color: "#0891B2",
    bg: "#ECFEFF" },
  {
    id: "loans",
    icon: Wallet,
    titleKey: "menu.credits",
    descKey: "qa_loans_desc",
    color: "#D97706",
    bg: "#FFFBEB" },
  {
    id: "account",
    icon: Wallet,
    titleKey: "menu.myAccounts",
    descKey: "qa_account_desc",
    color: "#2563EB",
    bg: "#EFF6FF" },
  {
    id: "cheques",
    icon: Receipt,
    titleKey: "cheques.title",
    descKey: "qa_cheques_desc",
    color: "#DC2626",
    bg: "#FEF2F2" },
  {
    id: "placements",
    icon: TrendingUp,
    titleKey: "menu.placements",
    descKey: "qa_placements_desc",
    color: "#059669",
    bg: "#ECFDF5" },
  {
    id: "exchange",
    icon: DollarSign,
    titleKey: "menu.exchangeRates",
    descKey: "qa_exchange_desc",
    color: "#CA8A04",
    bg: "#FEFCE8" },
  {
    id: "savings",
    icon: Banknote,
    titleKey: "savingPlans.title",
    descKey: "qa_savings_desc",
    color: "#059669",
    bg: "#ECFDF5" },
  {
    id: "rib",
    icon: Receipt,
    titleKey: "menu.consultRib",
    descKey: "qa_rib_desc",
    color: "#0EA5E9",
    bg: "#F0F9FF" },
  {
    id: "card_reload",
    icon: CreditCard,
    titleKey: "menu.cardReload",
    descKey: "qa_card_reload_desc",
    color: "#0284C7",
    bg: "#F0F9FF" },
  {
    id: "bills",
    icon: Receipt,
    titleKey: "bills.title",
    descKey: "qa_bills_desc",
    color: "#EA580C",
    bg: "#FFF7ED" },
];
